sonar.projectKey=utkarshutt2706_expense-splitter
sonar.organization=utkarshutt2706
sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**,src/lib/api/generated/**
sonar.coverage.exclusions=src/main.tsx,src/**/index.ts,src/vite-env.d.ts,src/lib/api/generated/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
