sonar.projectKey=utkarshutt2706_expense-splitter
sonar.organization=utkarshutt2706
sonar.sources=src
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
